--- 
- 
  become: true
  handlers: 
    - 
      name: docker
      service: ~
      state: restarted
  hosts: docker
  tasks: 
    - 
      apt: 
        name: "{{item}}"
        state: present
        update_cache: true
      loop: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      name: "installa dipendenze"
    - 
      apt_key: 
        state: present
        url: "https://download.docker.com/linux/ubuntu/gpg"
      name: "aggiungi chiave GPG"
    - 
      apt_repository: 
        repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
        state: present
      name: "aggiungi repository docker"
    - 
      apt: 
        name: "{{item}}"
        state: latest
        update_cache: true
      loop: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      name: "installa docker"
    - 
      name: "assicurati che docker sia attivo"
      service: 
        enabled: true
        name: docker
        state: started
